name: Build 3.x

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      CLOUSEAU_LOG: deps/couchdb.main/dev/logs/clouseau1.log
    steps:
      - uses: actions/checkout@v4
      - run: git config advice.detachedHead false
      - name: Comment out tools not available in mise
        run: sed -i 's/^spotbugs /#spotbugs /' .tool-versions
      - name: Install mise & tools
        uses: jdx/mise-action@v2
        with:
          install: true

      - name: Unit tests
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 3
          command: mise exec -- make test
      - name: Restart test
        run: mise exec -- make restart-test
      - name: RPC tests (zeunit)
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 3
          command: mise exec -- make zeunit
      - name: Concurrent RPC tests (zeunit)
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 3
          command: mise exec -- make concurrent-zeunit-tests
      - name: Syslog tests
        run: mise exec -- make syslog-tests || cat $CLOUSEAU_LOG
      - name: Elixir tests
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 3
          command: mise exec -- make ci-elixir || cat $CLOUSEAU_LOG
      - name: Metrics tests (mango)
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 3
          command: mise exec -- make metrics-tests || cat $CLOUSEAU_LOG
