name: Release 3.x

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    name: Release of clouseau-{version}-dist.zip
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git config advice.detachedHead false
      - name: Set ENV for github-release
        run: |
          echo "RELEASE_TAG=${GITHUB_REF:10}" >> $GITHUB_ENV
          echo "RELEASE_NAME=$GITHUB_WORKFLOW" >> $GITHUB_ENV
      - name: Comment out tools not available in mise
        run: sed -i 's/^spotbugs /#spotbugs /' .tool-versions
      - name: Install mise & tools
        uses: jdx/mise-action@v2
        with:
          install: true

      - name: Test
        run: mise exec -- make test
      - name: Generate artifacts
        run: mise exec -- make artifacts
      - name: List artifacts
        run: ls artifacts
      - name: Create release
        run: mise exec -- make release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
